# Generated by Django 4.2.7 on 2023-11-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmarks',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
