# Generated by Django 4.2.7 on 2023-11-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentsmarks_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmarks',
            name='totalmarks',
            field=models.IntegerField(default=0),
        ),
    ]
